config/routes.rb
Rails.application.routes.draw do

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games do
   resources :likes, only: [:create, :destroy]
   resources :comments, only: [:create]
  end
 
  resources :practices 
  resources :blogs

  devise_for :users, controllers: {   registrations: 'users/registrations',
  sessions: 'users/sessions' }

  resources :users, only: [:show] # ユーザーマイページへのルーティング
  root 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord

    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

    mount_uploader :image, ImageUploader
    
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :game
  belongs_to :user

  validates_uniqueness_of :game_id, scope: :user_id
end

app/models/practice.rb
class Practice < ApplicationRecord

    belongs_to :user
    
    mount_uploader :image, ImageUploader
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :games, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
has_many :likes, dependent: :destroy
has_many :liked_games, through: :likes, source: :game
has_many :comments, dependent: :destroy

def already_liked?(game)
  self.likes.exists?(game_id: game.id)
end

mount_uploader :image, ImageUploader

validates :name, presence: true #追記
validates :profile, length: { maximum: 200 } #追記
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end
  
  def show
    @blog = Blog.find(params[:id])
  end

  def create
    Blog.create(blog_parameter)
    redirect_to blogs_path
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      game = Game.find(params[:game_id])
      comment = game.comments.build(comment_params) #buildを使い、contentとgame_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
  end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  def new
    @game = Game.new
  end

  def create
      game = Game.new(games_params)
  
      game.user_id = current_user.id  

      if game.save
        redirect_to action: "index"
      else
        redirect_to action: "new"
      end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path, notice:"削除しました"
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_parameter)
      redirect_to games_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  def index
      @games = Game.all
  end

  def start_time
    self.start_at #self.の後はsimple_calendarに表示させるためのカラムを指定
  end


  
  
  def show
    @game = Game.find(params[:id])

    @comments = @game.comments
    @comment = Comment.new
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path, notice:"削除しました"
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_parameter)
      redirect_to games_path, notice: "編集しました"
    else
      render 'edit'
    end
    @comments = @game.comments
    @comment = Comment.new

  end



  private
  def games_params
    params.require(:game).permit(:level, :hand, :result, :count, :about, :start_time, :title, :image) 
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(game_id: params[:game_id]) #user_idとgame_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(game_id: params[:game_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end

end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController

    def create
        practice = Practice.new(practice_params)
    
        practice.user_id = current_user.id  #追記
    
        if practice.save
          redirect_to action: "index"
        else
          redirect_to action: "new"
        end
    end

    
    def index
        @practices = Practice.all
    end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  #ログイン後のリダイレクト先
def after_sign_in_path_for(resource)
  user_path(current_user.id)
end 
#ログアウト後のリダイレクト先
def after_sign_out_path_for(resource)
  games_path
end 
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id]) 
    end

end
#kkk

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

    <div class="title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
      <div class="time">
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time %>
    </div>
  
    <div class="content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
  
  
    <div class="submit">
      <%= form.submit %>
    </div>
  
  <% end %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>自分の日記</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog.id) %></td>
        <td><%= link_to 'Destroy',blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日記をかく', new_blog_path %>

<%= month_calendar events: @blogs do |date, blogs| %>
  <%= date.day %>

  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog %>
    </div>
  <% end %>
<% end %>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

    <div class="title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
      <div class="time">
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time %>
    </div>
  
    <div class="content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
  
  
    <div class="submit">
      <%= form.submit %>
    </div>

    
  
  <% end %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>時間</strong>
  <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/games/index.html.erb
<div class="games_container">
<%= link_to "新規投稿", new_game_path %>
<%#= link_to '日記をかく', new_game_path %>
<%#= month_calendar events: @games do |date, blogs| %>
  <%#= date.day %>
<%# end %>

   <% @games.each do |t| %>
    <div class="game">
      <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
      <%= t.user.email %>
    <div class="level">
      <%= t.level %>  
    </div> 
      <%= t.hand %> 
      <%= t.result %> 
      <%= t.count %> 
      <%= t.about %> 
      <%= image_tag t.image_url, size: "250x200" if t.image? %>  
      <%= link_to "詳細へ", game_path(t.id) %> 
    </div>
 

<% if user_signed_in? %>
    <% if current_user.already_liked?(t) %>
        <%= button_to game_like_path(id: t.id, game_id: t.id), method: :delete do %>
            <p>いいねを取り消す</p><%= t.likes.count %>
        <% end %>
    <% else %>
        <%= button_to game_likes_path(id: t.id, game_id: t.id), method: :post do %>
            <p>いいね</p><%= t.likes.count %>
        <% end %>
    <% end %>
<% else %>
    <p>いいねの数 = </p><%= t.likes.count %>
<% end %>

<% if current_user.already_liked?(t) %>
 
 <% end %>
</div>
<% end %>

app/views/games/new.html.erb
<h1>(自分の題名)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @game do |f| %>

  <div class="title">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="time">
    <%= f.label :start_time %>
    <%= f.time_select :start_time, required: true %>
  </div>


  #データ型がstringで選択式の入力フォーム
  <div class="field">
    <%= f.label :level  %>
    <%= f.select :level, 
    [["無", "無"],   
    ["初", "初"], 
    ["2", "2"], 
    ["3", "3"], 
    ["4以上" , "4以上"]], include_blank: "選択して下さい" %>
  </div>

  #データ型がstringで選択式の入力フォーム
  <div class="field">
    <%= f.label :hand  %>
    <%= f.select :hand, 
    [["右", "右"],   
    ["左", "左"], 
    ["不明", "不明"]],  include_blank: "選択して下さい"%>
  </div>

  #データ型がstringで選択式の入力フォーム
  <div class="field">
    <%= f.label :result  %>
    <%= f.select :result, 
    [["勝ち", "勝ち"],   
    ["負け", "負け"], 
    ["途中", "途中"]],  include_blank: "選択して下さい" %>
  </div>

  #データ型がintegerで数字のみを入力するフォーム
  <div class="field">
    <%= f.label :count  %>
    <%= f.number_field :count, :size => 10 %>
  </div>

  #データ型がtextで自由記述の入力フォーム
  <div class="field">
    <%= f.label :about  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", games_path %>

app/views/games/show.html.erb
<h1>Karutageek</h1>
<h3>投稿</h3>
<div class="game">
  <p><%= @game.created_at %></p>  
  <p><%= @game.level %> </p>  
  <p><%= @game.hand %> </p>
  <p><%= @game.result %> </p>
  <p><%= @game.count %></p> 
  <p><%= @game.about %></p>
  <%= image_tag @game.image_url, size: "250x200" if @game.image? %>  

    <% if user_signed_in? %>
      <% if current_user.already_liked?(@game) %>
        <%= button_to game_like_path(@game), method: :delete do %>
          <p>いいねを取り消す</p><%= @game.likes.count %>
        <% end %>
      <% else %>
        <%= button_to game_likes_path(@game), method: :post do %>
          <p>いいね</p><%= @game.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @game.likes.count %>
    <% end %>

    <div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
      <div>
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
      </div>
        <br>
    <% end %>
  
    <% if user_signed_in? %>
      <%= form_with(model: [@game, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
    <% end %>
  </div>
  
  <%= link_to "編集する", edit_game_path(@game.id) %>

</div>

<h2>いいねしたユーザー</h2>
<% @game.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>



<%= link_to "Game一覧に戻る", games_path %>

app/views/practices/index.html.erb
<div class="practices-container">
  <% @practices.each do |t| %>
    <div class="practice">
      <%= t.user.email %> ＃追記
    </div>
  <% end %>